N = 51;
w1 = ones(1,N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/(N));
figure('NumberTitle', 'off', 'Name', 'rectangular window');
subplot(3,3,1);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 51');
subplot(3,3,2);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,3);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');

N = 75;
w1 = ones(1,N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/N);
subplot(3,3,4);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 75');
subplot(3,3,5);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,6);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');

N = 101;
w1 = ones(1,N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/N);
subplot(3,3,7);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 101');
subplot(3,3,8);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,9);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');
%-----------------------

N = 51;
w1 = bartlett(N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/(N));
figure('NumberTitle', 'off', 'Name', 'bartlett window');
subplot(3,3,1);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 51');
subplot(3,3,2);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,3);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');

N = 75;
w1 = bartlett(N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/N);
subplot(3,3,4);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 75');
subplot(3,3,5);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,6);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');

N = 101;
w1 = bartlett(N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/N);
subplot(3,3,7);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 101');
subplot(3,3,8);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,9);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');
%-----------------------

N = 51;
w1 = hamming(N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/(N));
figure('NumberTitle', 'off', 'Name', 'hamming window');
subplot(3,3,1);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 51');
subplot(3,3,2);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,3);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');

N = 75;
w1 = hamming(N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/N);
subplot(3,3,4);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 75');
subplot(3,3,5);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,6);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');

N = 101;
w1 = hamming(N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/N);
subplot(3,3,7);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 101');
subplot(3,3,8);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,9);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');
%-----------------------

N = 51;
w1 = hann(N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/(N));
figure('NumberTitle', 'off', 'Name', 'hanning window');
subplot(3,3,1);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 51');
subplot(3,3,2);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,3);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');

N = 75;
w1 = hann(N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/N);
subplot(3,3,4);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 75');
subplot(3,3,5);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,6);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');

N = 101;
w1 = hann(N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/N);
subplot(3,3,7);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 101');
subplot(3,3,8);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,9);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');
%-----------------------

N = 51;
w1 = blackman(N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/(N));
figure('NumberTitle', 'off', 'Name', 'blackman window');
subplot(3,3,1);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 51');
subplot(3,3,2);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,3);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');

N = 75;
w1 = blackman(N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/N);
subplot(3,3,4);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 75');
subplot(3,3,5);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,6);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');

N = 101;
w1 = blackman(N);
h1 = fft(w1,500);
H1 = fftshift(h1);
y1 = 20*log10(abs(H1)/N);
subplot(3,3,7);
plot(w1);grid on;
xlabel('N');
ylabel('w1');
title('window N = 101');
subplot(3,3,8);
plot(y1);ylim([-100,10]);grid on;
xlabel('frequency');
ylabel('|Wnorm|');
title('|Wnorm| in db');
subplot(3,3,9);
plot(angle(H1));grid on;
xlabel('frequency');
ylabel('phase(Wnorm)');
title('phase of Wnorm');
%-----------------------
