fs = 10000;
fc = 2000;
d1 = 1;
d2 = 40;
N = 12;
n = 2001;
[b1,a1] = butter(N,fc/fs/2);
[b2,a2] = cheby1(N,d1,fc/fs/2);
[b3,a3] = cheby2(N,d2,fc/fs/2);
[b4,a4] = ellip(N,d1,d2,fc/fs/2);
[h1,w1] = freqz(b1,a1,n);
[h2,w2] = freqz(b2,a2,n);
[h3,w3] = freqz(b3,a3,n);
[h4,w4] = freqz(b4,a4,n);
figure;subplot(2,2,1);
plot(w1/pi,20*log10(abs(h1)));ylim([-450 0]);grid on;
xlabel('Normalized freq');
ylabel('magnitude response');
title('butterworth filter');
subplot(2,2,2);
plot(w2/pi,20*log10(abs(h2)));ylim([-450 0]);grid on;
xlabel('Normalized freq');
ylabel('magnitude response');
title('chebyshev1 filter');
subplot(2,2,3);
plot(w3/pi,20*log10(abs(h3)));ylim([-450 0]);grid on;
xlabel('Normalized freq');
ylabel('magnitude response');
title('chebyshev2 filter');
subplot(2,2,4);
plot(w4/pi,20*log10(abs(h4)));ylim([-450 0]);grid on;
xlabel('Normalized freq');
ylabel('magnitude response');
title('elliptic filter');

figure;subplot(2,2,1);
plot(w1/pi,angle(h1));grid on;
xlabel('Normalized freq');
ylabel('phase response');
title('butterworth filter');
subplot(2,2,2);
plot(w2/pi,angle(h2));grid on;
xlabel('Normalized freq');
ylabel('phase response');
title('chebyshev1 filter');
subplot(2,2,3);
plot(w3/pi,angle(h3));grid on;
xlabel('Normalized freq');
ylabel('phase response');
title('chebyshev2 filter');
subplot(2,2,4);
plot(w4/pi,angle(h4));grid on;
xlabel('Normalized freq');
ylabel('phase response');
title('elliptic filter');